app_auth0/urls.py
from django.urls import path

from app_auth0.views import (callback, index, login, logout, private,
                             private_scoped, public)

app_name = "app_auth0"

# for auth0 api
urlpatterns = [
    # for Auth0 api
    path("api/v1/auth0/public", public),
    path("api/v1/auth0/private", private),
    path("api/v1/auth0/private-scoped", private_scoped),
    # for Auth0 web
    path("auth0/", index, name="auth0_index"),
    path("auth0/login", login, name="auth0_login"),
    path("auth0/logout/", logout, name="auth0_logout"),
    path("auth0/callback", callback, name="auth0_callback"),
]

test_appstorespy_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (SpectacularAPIView, SpectacularRedocView,
                                   SpectacularSwaggerView)
from debug_toolbar import urls as debug_urls
from regloginout.views import index
from test_appstorespy_1.settings import API_VERTION
from uploader.views import CeleryStatus
from django.views.generic import TemplateView

api_vertion = API_VERTION

urlpatterns = [
    path('', index, name='index'),
    path("admin/", admin.site.urls),
    path('__debug__/', include(debug_urls)), # debug toolbar URLS
    path(f"api/{api_vertion}/", include("regloginout.urls", namespace="regloginout")),
    path(f"api/{api_vertion}/", include("uploader.urls", namespace="uploader")),
    path(f"api/{api_vertion}/", include("uploader_mongo.urls", namespace="uploader_mongo")),
    path(
        f"api/{api_vertion}/celery_status/",
        CeleryStatus.as_view(),
        name="celery_status",
    ),
    # for allauth
    path("accounts/", include("allauth.urls")),
    # for auth0
    path("", include("app_auth0.urls", namespace="app_auth0")),
    path("", include("social_django.urls")),
    # for django-silk
    path("silk/", include("silk.urls", namespace="silk")),
    # доступ к описанию проекта из API
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploader/urls.py
from django.urls import path

from test_appstorespy_1.settings import API_VERTION
# from uploader.views import (FileDeleteAPIView, FileDownloadAPIView,
#                             FileProcessingAPIView, FileUploadAPIView)
from uploader.views import FileUploadAPIView

api_vertion = API_VERTION

app_name = "uploader"

urlpatterns = [
    path("file/", FileUploadAPIView.as_view(), name="file_upload"),
]

app_auth0/models.py
from django.db import models

# Create your models here.

app_auth0/views.py
# for auth0 web

import json
from urllib.parse import quote_plus, urlencode

from authlib.integrations.django_client import OAuth
from django.conf import settings
from django.shortcuts import redirect, render
from django.urls import reverse

oauth = OAuth()

oauth.register(
    "auth0",
    client_id=settings.AUTH0_CLIENT_ID,
    client_secret=settings.AUTH0_CLIENT_SECRET,
    client_kwargs={
        "scope": "openid profile email",
    },
    server_metadata_url=f"https://{settings.AUTH0_DOMAIN}/.well-known/openid-configuration",
)


def login(request):
    return oauth.auth0.authorize_redirect(
        request, request.build_absolute_uri(reverse("app_auth0:auth0_callback"))
    )


def callback(request):
    token = oauth.auth0.authorize_access_token(request)
    request.session["user"] = token
    return redirect(request.build_absolute_uri(reverse("auth0_index")))


def logout(request):
    request.session.clear()

    return redirect(
        f"https://{settings.AUTH0_DOMAIN}/v2/logout?"
        + urlencode(
            {
                "returnTo": request.build_absolute_uri(reverse("auth0_index")),
                "client_id": settings.AUTH0_CLIENT_ID,
            },
            quote_via=quote_plus,
        ),
    )


def index(request):
    return render(
        request,
        "app_auth0/index.html",
        context={
            "session": request.session.get("user"),
            "pretty": json.dumps(request.session.get("user"), indent=4),
        },
    )


# from django.contrib.auth import logout as django_logout
# from django.conf import settings
# from django.contrib.auth.decorators import login_required
#
#
# def index(request):
#     return render(request, 'app_auth0/index.html')
#
#
# @login_required
# def logout(request):
#     django_logout(request)
#     domain = settings.SOCIAL_AUTH_AUTH0_DOMAIN
#     client_id = settings.SOCIAL_AUTH_AUTH0_KEY
#     return_to = 'http://127.0.0.1:8000' # this can be current domain
#     return redirect(f'https://{domain}/v2/logout?client_id={client_id}&returnTo={return_to}')


# for auth0 api
from functools import wraps

import jwt
from django.http import JsonResponse


def get_token_auth_header(request):
    """Obtains the Access Token from the Authorization Header"""
    auth = request.META.get("HTTP_AUTHORIZATION", None)
    parts = auth.split()
    token = parts[1]

    return token


def requires_scope(required_scope):
    """Determines if the required scope is present in the Access Token
    Args:
        required_scope (str): The scope required to access the resource
    """

    def require_scope(f):
        @wraps(f)
        def decorated(*args, **kwargs):
            token = get_token_auth_header(args[0])
            decoded = jwt.decode(token, verify=False)
            if decoded.get("scope"):
                token_scopes = decoded["scope"].split()
                for token_scope in token_scopes:
                    if token_scope == required_scope:
                        return f(*args, **kwargs)
            response = JsonResponse(
                {"message": "You don't have access to this resource"}
            )
            response.status_code = 403
            return response

        return decorated

    return require_scope


# for auth0 api
from django.http import JsonResponse
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny


@api_view(["GET"])
@permission_classes([AllowAny])
def public(request):
    return JsonResponse(
        {
            "message": "Hello from a public endpoint! You don't need to be authenticated to see this."
        }
    )


@api_view(["GET"])
def private(request):
    return JsonResponse(
        {
            "message": "Hello from a private endpoint! You need to be authenticated to see this."
        }
    )


@api_view(["GET"])
@requires_scope("read:messages")
def private_scoped(request):
    return JsonResponse(
        {
            "message": "Hello from a private endpoint! You need to be authenticated and have a scope of read:messages to see this."
        }
    )

templates/app_auth0/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
  </head>
  <body>
    <section class="hero is-info">
      <div class="hero-head">
        <nav class="navbar" role="navigation" aria-label="main navigation">
          <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start pl-2">
              <a href="/" class="navbar-item">Home</a>

            </div>
            <div class="navbar-end pr-2">
              <div class="navbar-item">
                <div class="buttons">
                  {% if user.is_authenticated %}
                  <a class="button is-primary" href="/logout/">Logout</a>
                  {% else %}
                  <a class="button is-primary" href="/login/auth0">Login</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </nav>
        <div class="hero-body">
          <div class="container has-text-centered">
            <p class="title">{% block main_title %}{% endblock %}</p>
            <p class="subtitle">{% block sub_title %}{% endblock %}</p>
          </div>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </section>
  </body>
</html>

templates/app_auth0/index.html
<html>
<head>
  <meta charset="utf-8" />
  <title>Auth0 Example</title>
</head>
<body>
{% if session %}
  <h1>Welcome {{session.userinfo.name}}!</h1>
  <p><a href="{% url 'app_auth0:auth0_logout' %}">Logout</a></p>
  <div><pre>{{pretty}}</pre></div>
{% else %}
  <h1>Welcome Guest</h1>
  <p><a href="{% url 'app_auth0:auth0_login' %}">Login</a></p>
{% endif %}
</body>
</html>

templates/app_auth0/index_1.html
{% extends 'app_auth0/base.html' %}
{% block title %}Home{% endblock %}
{% block main_title %}Public Feed{% endblock %}
{% block sub_title %}Leave a message for everyone to see!{% endblock %}
{% block content %}
{% endblock %}